name: 'SnowflakeGuid-sonar'

trigger:
 branches:
   exclude:
     - 'azure-pipelines'
   include:
     - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'SnowflakeGuid.sln'
  mainProject: 'SnowflakeGuid/SnowflakeGuid.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- checkout: self
  fetchDepth: 0
  clean: true
  fetchTags: true
  displayName: 'git checkout'
  enabled: true
  retryCountOnTaskFailure: 2

- task: SonarCloudPrepare@3
  inputs:
    SonarCloud: 'sonar snowflake'
    organization: 'hudsonventura'
    scannerMode: 'dotnet'
    projectKey: 'hudsonventura_SnowflakeGuid2'
    projectVersion: '1.0'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\**\*.test.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    diagnosticsEnabled: true


- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_21_X64'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
