name: 'SnowflakeIDGenerator-CI'

trigger:
 branches:
   include:
     - master
pr:
  branches:
    exclude:
      - '*'

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  mainProject: 'SnowflakeIDGenerator/SnowflakeIDGenerator.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Pipeline'

steps:
- checkout: self
  fetchDepth: 0
  clean: true
  fetchTags: true
  displayName: 'git checkout'
  enabled: true
  retryCountOnTaskFailure: 2

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'NuGet Restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    clean: true

- task: VSTest@3
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\bin\**\*.test.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: true
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    diagnosticsEnabled: true

- task: DotNetCoreCLI@2
  displayName: 'NuGet Pack'
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj;!**/*.Tests.csproj;!**/*.Test.csproj;!**/Examples/**/*.csproj'
    versioningScheme: 'off'

# - task: NuGetCommand@2
  # displayName: 'NuGet Push'
  # inputs:
    # command: 'push'
    # packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    # nuGetFeedType: 'external'
    # publishFeedCredentials: 'NuGet'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    publishLocation: 'pipeline'
